### ISSUE TITLE
tests fail?

### ISSUE THREAD

**Issue by wwood** [blowmage/minitest-rg#12]
Hi,

I'm attempting to package minitest-rg for the GNU Guix package manager, and I noticed that the tests seem to fail:
```
/tmp/minitest-rg$ rake test
/gnu/store/15i5z93xj8v1myqdh5d4d3apqyqzlnza-ruby-2.2.3/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; gem "minitest"; require "minitest/autorun"; require "test/test_minitest-rg.rb"' -- 
Run options: --seed 44015

# Running:

.FSE

Finished in 0.000852s, 4693.6071 runs/s, 2346.8035 assertions/s.

  1) Failure:
minitest-rg#test_0002_fails [/tmp/minitest-rg/test/test_minitest-rg.rb:13]:
Failure should be RED.
Expected: 1
  Actual: 2


  2) Error:
minitest-rg#test_0003_error:
RuntimeError: Error should be YELLOW
    /tmp/minitest-rg/test/test_minitest-rg.rb:18:in `block (2 levels) in <top (required)>'

4 runs, 2 assertions, 1 failures, 1 errors, 1 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [/gnu/store/15i5z93xj8v1myqdh5d4d3apqyqzlnz...]
/home/ben/.guix-profile/lib/ruby/gems/2.2.0/gems/hoe-3.13.1/lib/hoe/test.rb:83:in `block in define_test_tasks'
Tasks: TOP => test
(See full trace by running task with --trace)
```
Do they normally fail? Am I doing something untoward?

Thanks,
ben

**Comment by grosser** [comment]
same here ... so I guess that is expected ... no travis is setup afaik ... so who knows when this broke ...

**Comment by grosser** [comment]
it is expected to fail / it shows all the pretty colors ... so just ignore ... fix PR:
https://github.com/blowmage/minitest-rg/pull/13/files
